### ISSUE TITLE
kmod-33: FAIL testsuite/test-user

### ISSUE THREAD

**Issue by jengelh** [kmod-project/kmod#84]
Testsuite of kmod-33 fails when `--with-module-directory=/usr/lib/modules` is used during configure:

```
FAIL: testsuite/test-user
=========================

module mod-loop-b not found in directory /home/abuild/rpmbuild/BUILD/kmod-33/testsuite/rootfs/test-user/lib/modules/4.4.4/
TESTSUITE: running test_user_weakdep, in forked context
TESTSUITE: ERR: 'test_user_weakdep' [17992] exited with return code 1
TESTSUITE: ERR: FAILED: test_user_weakdep
TESTSUITE: ------
FAIL testsuite/test-user (exit status: 1)
```

It would appear there is a hardcoded path somewhere, and found in the git tree here:

```
$ git grep es/4.4.4
testsuite/rootfs-pristine/test-modprobe/module-param-kcmdline/correct.txt:insmod /lib/modules/4.4.4/kernel/mod-simple.ko foo bar=1 
testsuite/rootfs-pristine/test-modprobe/show-depends/correct-mod-simple.txt:insmod /lib/modules/4.4.4/kernel/mod-simple.ko 
testsuite/rootfs-pristine/test-modprobe/show-depends/correct.txt:insmod /lib/modules/4.4.4/kernel/mod-loop-b.ko 
testsuite/rootfs-pristine/test-modprobe/show-depends/correct.txt:insmod /lib/modules/4.4.4/kernel/mod-loop-a.ko 
```

**Comment by lucasdemarchi** [comment]
Fixed by 05269d823fdc ("build: Add mod-weakdep.ko to cache")

Same warning as given https://lore.kernel.org/linux-modules/mngwezxuvjt5pj5lcayhipooxxk2zyailatrhgysyqa3xye4at@ylujurf3ytjw/

Due to security concerns I don't like to add binaries anymore and this will likely be removed in the next version. Distros only really need the kernel headers to be able to build the modules (and we can skip the tests for the non-native ones).

**Comment by jengelh** [comment]
Cherry-picking that commit onto v33 does not appear to resolve the test failure. Do we need other commits?

**Comment by lucasdemarchi** [comment]
ah... different issue. The test in question doesn't handle different module directory.
590074281e84 ("testsuite: fix path for test-user")
